create database classified;

use classified;

CREATE TABLE USER_DETAILS(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONTACT_NO VARCHAR(100) NOT NULL,
	ALTERNATE_NO VARCHAR(100),
	EMAIL_ID VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	USER_ID VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY ( ID )
);

ALTER TABLE CATEGORY ADD IMG_LOC VARCHAR(100) AFTER DESCRIPTION;

CREATE TABLE SUB_CATEGORY(
	ID INT NOT NULL AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	CODE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY ( ID ),
	CONSTRAINT fk_CategoryId FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE ITEM_DETAILS(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	SUB_CATEGORY_ID INT NOT NULL,
	PRICE INT NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	ACTIVE_FLAG CHAR(1) NOT NULL,
	SELLER_ID INT NOT NULL,
	CREATED_TS TIMESTAMP,
	UPDATED_TS TIMESTAMP,
	PRIMARY KEY ( ID ),
	CONSTRAINT fk_SubCategoryId FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY(ID)
);

CREATE TABLE ITEM_SUBSCRIPTION(
	SUBSCRIBER_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	ACTIVE_FLAG CHAR(1) NOT NULL,
	PRIMARY KEY ( SUBSCRIBER_ID, ITEM_ID, CATEGORY_ID ),
	CONSTRAINT fk_SubscriberId FOREIGN KEY (SUBSCRIBER_ID) REFERENCES USER_DETAILS(ID),
	CONSTRAINT fk_ItemId FOREIGN KEY (ITEM_ID) REFERENCES ITEM_DETAILS(ID),
	CONSTRAINT fk_ItemSub_CategoryId FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);